const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ERROR: 'SET_USER_ERROR',
    UPDATE_TICKET_LIST: 'UPDATE_TICKET_LIST',
    UPDATE_POSITIONS_LIST: 'UPDATE_POSITIONS_LIST',
    LOG_IN_START: 'LOG_IN_START',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    LOG_OUT_START: 'LOG_OUT_START',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
};

export default userActionTypes